### ISSUE TITLE
Demeaning  the moment conditions

### ISSUE THREAD

**Issue by khof312** [chrisconlon/Grad-IO#5]
https://github.com/chrisconlon/Grad-IO/blob/90a9f5889bb824712a990facb6322755598360d4/Extra%20Notes/GMM/gmmnotes.tex#L139

Not sure if this is an issue or a question, maybe I just misunderstood :) 

Here, you say it's almost always a bad idea not to demean. However, below (linear IV estimator), you give $\hat{S}$ without demeaning because $E(z_i \epsilon_i) = 0$. So, perhaps it makes sense either to explain when it is OK not to demean, or else we should demean $\hat{S}$ below too?

**Comment by chrisconlon** [comment]
Yes. How you construct a estimate of $\hat{S}^{-1}$ is up to you. However, you should almost always de-mean when you construct it in practice. In theory because the gradient is zero at the maximum this shouldn't matter but in practice it can be substantial.
